import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'app_colors.freezed.dart';

@Freezed(copyWith: false)
class AppColors with _$AppColors implements ThemeExtension<AppColors> {
  const factory AppColors({
    required Color primary,
    required Color orange,
    required Color discountColor,

    required Color red,
    required Color redBright,
    required Color green,
    required Color greenlight,
    required Color greenBright,
    required Color yellow,
    required Color starYellow,
    required Color aqua,
    required Color ticketStatusP,

    required Color text,
    required Color textLight,
    required Color textMedium,
    required Color toolbarText,

    required Color background,
    required Color backgroundGray,
    required Color scaffoldBackground,
    required Color drawerTopBg,
    required Color ticketBg,
    required Color solitude,
    required Color meNot,
    required Color titanWhite,
    required Color pattensBlue,

    required Color white,
    required Color black,
    required Color blackLight,

    required Color whiteSmoke,
    required Color grayLight,
    required Color concrete,
    required Color silverChalice,
    required Color graySmallLight,
    required Color grayDark,
    required Color gray,
    required Color blackBark,
    required Color categoryColor,
    required Color mineShaft,
    required Color codGary,

    required Color borderColor,
    required Color borderLight,
    required Color borderLightGray,
    required Color replyBorderColor,

    required Color candleLight,
    required Color scampi,
    required Color geraldine,
    required Color salmon,
    required Color shamrock,

    required Color progressBarColor,
    required Color progressBarActiveColor,

    required Color button,
    required Color telegram,
    required Color info,
    required Color highlighter,
    required Color primaryDark,
    required Color secondaryLight,
    required Color secondaryDark,
    required Color unselectedLabel,
    required Color selectedLabel,

    required Color spotlightBlueLight,
    required Color spotlightBlue,
    required Color spotlightBlueDark,
    required Color spotlightBlueShadow,
    required Color spotlightBlueVeryLight,

    required Color ticketNew,
    required Color ticketOpen,
    required Color ticketHold,
    required Color ticketClosed,

    required Color darkBlueNav,
    required Color darkBlueBg,
    required Color lightYellowBg,
    required Color linkBlue,
  }) = _AppColors;

  const AppColors._();

  @override
  Type get type => AppColors;

  factory AppColors.light() => const AppColors(
    primary: Color(0xFF00A8E8),
    orange: Color(0xFFFF5722),
    discountColor: Color(0xFFFF5722),

    red: Color(0xFFFF2222),
    redBright: Color(0xFFDC2828),
    green: Color(0xFF2e9934),
    greenlight: Color(0xFF13D55F),
    greenBright: Color(0x33018000),
    yellow: Color(0xFFFBCA2C),
    starYellow: Color(0xFFFFC107),
    aqua: Color(0xFF37FFF1),
    ticketStatusP: Color(0xFF1CBB76),

    text: Color(0xFF333333),
    textLight: Color(0xFF777777),
    textMedium: Color(0xFF555555),
    toolbarText: Color(0xFFFFFFFF),

    background: Color(0xFFFFFFFF),
    backgroundGray: Color(0xFFF5F5F5),
    scaffoldBackground: Color(0xFFfbfbfb),
    drawerTopBg: Color(0xFF333333),
    ticketBg: Color(0xFFF2F2F2),
    solitude: Color(0xFFE8F3FF),
    meNot: Color(0xFFFFF1EF),
    titanWhite: Color(0xFFEEF0FF),
    pattensBlue: Color(0xFFD8F1FF),

    white: Color(0xFFFFFFFF),
    black: Color(0xFF000000),
    blackLight: Color(0x4D000000),
    whiteSmoke: Color(0xFFF5F5F5),
    grayLight: Color(0xFFF5F5F5),
    concrete: Color(0xFFF3F3F3),
    silverChalice: Color(0xFF9F9F9F),
    graySmallLight: Color(0xFF8A8A8A),
    grayDark: Color(0xFF707070),
    gray: Color(0xFF5E5E5E),
    blackBark: Color(0xFF666666),
    categoryColor: Color(0xFF666666),
    mineShaft: Color(0xFF313131),
    codGary: Color(0xFF201B1B),

    borderColor: Color(0xFFEFEFEF),
    borderLight: Color(0xFFF0F0F0),
    borderLightGray: Color(0xFFEEEEEE),
    replyBorderColor: Color(0xFFE9E9E9),

    candleLight: Color(0xFFFBC910),
    scampi: Color(0xFF6771A8),
    geraldine: Color(0xFFFF8484),
    salmon: Color(0xFFFF8F6B),
    shamrock: Color(0xFF52D89E),

    progressBarColor: Color(0xFF443600),
    progressBarActiveColor: Color(0xFFE8BD12),

    button: Color(0xFF3483FF),
    telegram: Color(0xFF2599D6),
    info: Color(0xFFF4DD43),
    highlighter: Color(0xFFFF5722),
    primaryDark: Color(0xFF1299E8),
    secondaryLight: Color(0xFFF5F5F5),
    secondaryDark: Color(0xFF333333),
    unselectedLabel: Color(0xFF666666),
    selectedLabel: Color(0xFF333333),

    spotlightBlueLight: Color(0xFF81D4FA),
    spotlightBlue: Color(0xFF64B5F6),
    spotlightBlueDark: Color(0xFF1976D2),
    spotlightBlueShadow: Color(0xFF0288D1),
    spotlightBlueVeryLight: Color(0xFFE1F5FE),
    ticketNew: Color(0xFFD82735),
    ticketOpen: Color(0xFF0079E7),
    ticketHold: Color(0xFFFFCB25),
    ticketClosed: Color(0xFFB21F35),
    darkBlueNav: Color(0xFF002B5B),
    darkBlueBg: Color(0xFF002F67),
    lightYellowBg: Color(0xFFFFF9E6),
    linkBlue: Color(0xFF0079C1),
  );

  factory AppColors.dark() => const AppColors(
    primary: Color(0xFF00A8E8),
    orange: Color(0xFFFF5722),
    discountColor: Color(0xFFFF5722),

    red: Color(0xFFFF2222),
    redBright: Color(0xFFDC2828),
    green: Color(0xFF2e9934),
    greenlight: Color(0xFF13D55F),
    greenBright: Color(0x33018000),
    yellow: Color(0xFFFBCA2C),
    starYellow: Color(0xFFFFC107),
    aqua: Color(0xFF37FFF1),
    ticketStatusP: Color(0xFF1CBB76),

    text: Color(0xFFFFFFFF),
    textLight: Color(0xFFBBBBBB),
    textMedium: Color(0xFFDDDDDD),
    toolbarText: Color(0xFFFFFFFF),

    background: Color(0xFF333333),
    backgroundGray: Color(0xFF1E1E1E),
    scaffoldBackground: Color(0xFF121212),
    drawerTopBg: Color(0xFF333333),
    ticketBg: Color(0xFFF2F2F2),
    solitude: Color(0xFFE8F3FF),
    meNot: Color(0xFFFFF1EF),
    titanWhite: Color(0xFFEEF0FF),
    pattensBlue: Color(0xFFD8F1FF),

    white: Color(0xFFFFFFFF),
    black: Color(0xFF000000),
    blackLight: Color(0x4D000000),

    whiteSmoke: Color(0xFFF5F5F5),
    grayLight: Color(0xFFF5F5F5),
    concrete: Color(0xFFF3F3F3),
    silverChalice: Color(0xFF9F9F9F),
    graySmallLight: Color(0xFF8A8A8A),
    grayDark: Color(0xFF707070),
    gray: Color(0xFF5E5E5E),
    blackBark: Color(0xFF666666),
    categoryColor: Color(0xFF666666),
    mineShaft: Color(0xFF313131),
    codGary: Color(0xFF201B1B),

    borderColor: Color(0xFFEFEFEF),
    borderLight: Color(0xFF2A2A2A),
    borderLightGray: Color(0xFFEEEEEE),
    replyBorderColor: Color(0xFFE9E9E9),

    candleLight: Color(0xFFFBC910),
    scampi: Color(0xFF6771A8),
    geraldine: Color(0xFFFF8484),
    salmon: Color(0xFFFF8F6B),
    shamrock: Color(0xFF52D89E),

    progressBarColor: Color(0xFF443600),
    progressBarActiveColor: Color(0xFFE8BD12),

    button: Color(0xFF3483FF),
    telegram: Color(0xFF2599D6),
    info: Color(0xFFF4DD43),
    highlighter: Color(0xFFFF5722),
    primaryDark: Color(0xFF1299E8),
    secondaryLight: Color(0xFFF5F5F5),
    secondaryDark: Color(0xFF333333),
    unselectedLabel: Color(0xFF666666),
    selectedLabel: Color(0xFFFFFFFF),
    spotlightBlueLight: Color(0xFF81D4FA),
    spotlightBlue: Color(0xFF64B5F6),
    spotlightBlueDark: Color(0xFF1976D2),
    spotlightBlueShadow: Color(0xFF0288D1),
    spotlightBlueVeryLight: Color(0xFFE1F5FE),
    ticketNew: Color(0xFFD82735),
    ticketOpen: Color(0xFF0079E7),
    ticketHold: Color(0xFFFFCB25),
    ticketClosed: Color(0xFFB21F35),
    darkBlueNav: Color(0xFF002B5B),
    darkBlueBg: Color(0xFF002F67),
    lightYellowBg: Color(0xFFFFF9E6),
    linkBlue: Color(0xFF0079C1),
  );

  @override
  AppColors copyWith({
    Color? primary,
    Color? orange,
    Color? discountColor,
    Color? red,
    Color? redBright,
    Color? green,
    Color? greenlight,
    Color? greenBright,
    Color? yellow,
    Color? starYellow,
    Color? aqua,
    Color? ticketStatusP,
    Color? text,
    Color? textLight,
    Color? textMedium,
    Color? toolbarText,
    Color? background,
    Color? backgroundGray,
    Color? scaffoldBackground,
    Color? drawerTopBg,
    Color? ticketBg,
    Color? solitude,
    Color? meNot,
    Color? titanWhite,
    Color? pattensBlue,
    Color? white,
    Color? black,
    Color? blackLight,
    Color? whiteSmoke,
    Color? grayLight,
    Color? concrete,
    Color? silverChalice,
    Color? graySmallLight,
    Color? grayDark,
    Color? gray,
    Color? blackBark,
    Color? categoryColor,
    Color? mineShaft,
    Color? codGary,
    Color? borderColor,
    Color? borderLight,
    Color? borderLightGray,
    Color? replyBorderColor,
    Color? candleLight,
    Color? scampi,
    Color? geraldine,
    Color? salmon,
    Color? shamrock,
    Color? progressBarColor,
    Color? progressBarActiveColor,
    Color? button,
    Color? telegram,
    Color? info,
    Color? highlighter,
    Color? primaryDark,
    Color? secondaryLight,
    Color? secondaryDark,
    Color? unselectedLabel,
    Color? selectedLabel,
    Color? spotlightBlueLight,
    Color? spotlightBlue,
    Color? spotlightBlueDark,
    Color? spotlightBlueShadow,
    Color? spotlightBlueVeryLight,
    Color? ticketNew,
    Color? ticketOpen,
    Color? ticketHold,
    Color? ticketClosed,
    Color? darkBlueNav,
    Color? darkBlueBg,
    Color? lightYellowBg,
    Color? linkBlue,
  }) {
    return AppColors(
      primary: primary ?? this.primary,
      orange: orange ?? this.orange,
      discountColor: discountColor ?? this.discountColor,
      red: red ?? this.red,
      redBright: redBright ?? this.redBright,
      green: green ?? this.green,
      greenlight: greenlight ?? this.greenlight,
      greenBright: greenBright ?? this.greenBright,
      yellow: yellow ?? this.yellow,
      starYellow: starYellow ?? this.starYellow,
      aqua: aqua ?? this.aqua,
      ticketStatusP: ticketStatusP ?? this.ticketStatusP,
      text: text ?? this.text,
      textLight: textLight ?? this.textLight,
      textMedium: textMedium ?? this.textMedium,
      toolbarText: toolbarText ?? this.toolbarText,
      background: background ?? this.background,
      backgroundGray: backgroundGray ?? this.backgroundGray,
      scaffoldBackground: scaffoldBackground ?? this.scaffoldBackground,
      drawerTopBg: drawerTopBg ?? this.drawerTopBg,
      ticketBg: ticketBg ?? this.ticketBg,
      solitude: solitude ?? this.solitude,
      meNot: meNot ?? this.meNot,
      titanWhite: titanWhite ?? this.titanWhite,
      pattensBlue: pattensBlue ?? this.pattensBlue,
      white: white ?? this.white,
      black: black ?? this.black,
      blackLight: blackLight ?? this.blackLight,
      whiteSmoke: whiteSmoke ?? this.whiteSmoke,
      grayLight: grayLight ?? this.grayLight,
      concrete: concrete ?? this.concrete,
      silverChalice: silverChalice ?? this.silverChalice,
      graySmallLight: graySmallLight ?? this.graySmallLight,
      grayDark: grayDark ?? this.grayDark,
      gray: gray ?? this.gray,
      blackBark: blackBark ?? this.blackBark,
      categoryColor: categoryColor ?? this.categoryColor,
      mineShaft: mineShaft ?? this.mineShaft,
      codGary: codGary ?? this.codGary,
      borderColor: borderColor ?? this.borderColor,
      borderLight: borderLight ?? this.borderLight,
      borderLightGray: borderLightGray ?? this.borderLightGray,
      replyBorderColor: replyBorderColor ?? this.replyBorderColor,
      candleLight: candleLight ?? this.candleLight,
      scampi: scampi ?? this.scampi,
      geraldine: geraldine ?? this.geraldine,
      salmon: salmon ?? this.salmon,
      shamrock: shamrock ?? this.shamrock,
      progressBarColor: progressBarColor ?? this.progressBarColor,
      progressBarActiveColor:
          progressBarActiveColor ?? this.progressBarActiveColor,
      button: button ?? this.button,
      telegram: telegram ?? this.telegram,
      info: info ?? this.info,
      highlighter: highlighter ?? this.highlighter,
      primaryDark: primaryDark ?? this.primaryDark,
      secondaryLight: secondaryLight ?? this.secondaryLight,
      secondaryDark: secondaryDark ?? this.secondaryDark,
      unselectedLabel: unselectedLabel ?? this.unselectedLabel,
      selectedLabel: selectedLabel ?? this.selectedLabel,
      spotlightBlueLight: spotlightBlueLight ?? this.spotlightBlueLight,
      spotlightBlue: spotlightBlue ?? this.spotlightBlue,
      spotlightBlueDark: spotlightBlueDark ?? this.spotlightBlueDark,
      spotlightBlueShadow: spotlightBlueShadow ?? this.spotlightBlueShadow,
      spotlightBlueVeryLight:
          spotlightBlueVeryLight ?? this.spotlightBlueVeryLight,
      ticketNew: ticketNew ?? this.ticketNew,
      ticketOpen: ticketOpen ?? this.ticketOpen,
      ticketHold: ticketHold ?? this.ticketHold,
      ticketClosed: ticketClosed ?? this.ticketClosed,
      darkBlueNav: darkBlueNav ?? this.darkBlueNav,
      darkBlueBg: darkBlueBg ?? this.darkBlueBg,
      lightYellowBg: lightYellowBg ?? this.lightYellowBg,
      linkBlue: linkBlue ?? this.linkBlue,
    );
  }

  @override
  AppColors lerp(ThemeExtension<AppColors>? other, double t) {
    if (other is! AppColors) return this;
    Color lerpColor(Color a, Color b) => Color.lerp(a, b, t)!;

    return copyWith(
      primary: lerpColor(primary, other.primary),
      orange: lerpColor(orange, other.orange),
      discountColor: lerpColor(discountColor, other.discountColor),
      red: lerpColor(red, other.red),
      redBright: lerpColor(redBright, other.redBright),
      green: lerpColor(green, other.green),
      greenlight: lerpColor(greenlight, other.greenlight),
      greenBright: lerpColor(greenBright, other.greenBright),
      yellow: lerpColor(yellow, other.yellow),
      starYellow: lerpColor(starYellow, other.starYellow),
      aqua: lerpColor(aqua, other.aqua),
      ticketStatusP: lerpColor(ticketStatusP, other.ticketStatusP),
      text: lerpColor(text, other.text),
      textLight: lerpColor(textLight, other.textLight),
      textMedium: lerpColor(textMedium, other.textMedium),
      toolbarText: lerpColor(toolbarText, other.toolbarText),
      background: lerpColor(background, other.background),
      backgroundGray: lerpColor(backgroundGray, other.backgroundGray),
      scaffoldBackground: lerpColor(
        scaffoldBackground,
        other.scaffoldBackground,
      ),
      drawerTopBg: lerpColor(drawerTopBg, other.drawerTopBg),
      ticketBg: lerpColor(ticketBg, other.ticketBg),
      solitude: lerpColor(solitude, other.solitude),
      meNot: lerpColor(meNot, other.meNot),
      titanWhite: lerpColor(titanWhite, other.titanWhite),
      pattensBlue: lerpColor(pattensBlue, other.pattensBlue),
      white: lerpColor(white, other.white),
      black: lerpColor(black, other.black),
      blackLight: lerpColor(blackLight, other.blackLight),
      whiteSmoke: lerpColor(whiteSmoke, other.whiteSmoke),
      grayLight: lerpColor(grayLight, other.grayLight),
      concrete: lerpColor(concrete, other.concrete),
      silverChalice: lerpColor(silverChalice, other.silverChalice),
      graySmallLight: lerpColor(graySmallLight, other.graySmallLight),
      grayDark: lerpColor(grayDark, other.grayDark),
      gray: lerpColor(gray, other.gray),
      blackBark: lerpColor(blackBark, other.blackBark),
      categoryColor: lerpColor(categoryColor, other.categoryColor),
      mineShaft: lerpColor(mineShaft, other.mineShaft),
      codGary: lerpColor(codGary, other.codGary),
      borderColor: lerpColor(borderColor, other.borderColor),
      borderLight: lerpColor(borderLight, other.borderLight),
      borderLightGray: lerpColor(borderLightGray, other.borderLightGray),
      replyBorderColor: lerpColor(replyBorderColor, other.replyBorderColor),
      candleLight: lerpColor(candleLight, other.candleLight),
      scampi: lerpColor(scampi, other.scampi),
      geraldine: lerpColor(geraldine, other.geraldine),
      salmon: lerpColor(salmon, other.salmon),
      shamrock: lerpColor(shamrock, other.shamrock),
      progressBarColor: lerpColor(progressBarColor, other.progressBarColor),
      progressBarActiveColor: lerpColor(
        progressBarActiveColor,
        other.progressBarActiveColor,
      ),
      button: lerpColor(button, other.button),
      telegram: lerpColor(telegram, other.telegram),
      info: lerpColor(info, other.info),
      highlighter: lerpColor(highlighter, other.highlighter),
      primaryDark: lerpColor(primaryDark, other.primaryDark),
      secondaryLight: lerpColor(secondaryLight, other.secondaryLight),
      secondaryDark: lerpColor(secondaryDark, other.secondaryDark),
      unselectedLabel: lerpColor(unselectedLabel, other.unselectedLabel),
      selectedLabel: lerpColor(selectedLabel, other.selectedLabel),
      spotlightBlueLight: lerpColor(
        spotlightBlueLight,
        other.spotlightBlueLight,
      ),
      spotlightBlue: lerpColor(spotlightBlue, other.spotlightBlue),
      spotlightBlueDark: lerpColor(spotlightBlueDark, other.spotlightBlueDark),
      spotlightBlueShadow: lerpColor(
        spotlightBlueShadow,
        other.spotlightBlueShadow,
      ),
      spotlightBlueVeryLight: lerpColor(
        spotlightBlueVeryLight,
        other.spotlightBlueVeryLight,
      ),
      ticketNew: lerpColor(ticketNew, other.ticketNew),
      ticketOpen: lerpColor(ticketOpen, other.ticketOpen),
      ticketHold: lerpColor(ticketHold, other.ticketHold),
      ticketClosed: lerpColor(ticketClosed, other.ticketClosed),
      darkBlueNav: lerpColor(darkBlueNav, other.darkBlueNav),
      darkBlueBg: lerpColor(darkBlueBg, other.darkBlueBg),
      lightYellowBg: lerpColor(lightYellowBg, other.lightYellowBg),
      linkBlue: lerpColor(linkBlue, other.linkBlue),
    );
  }
}

extension AppColorsX on BuildContext {
  AppColors? get maybeColors => Theme.of(this).extension<AppColors>();

  AppColors get colors {
    final theme = Theme.of(this);
    final ext = theme.extension<AppColors>();
    if (ext != null) return ext;

    assert(() {
      debugPrint(
        '[AppColors] Missing ThemeExtension<AppColors> in ThemeData.extensions; using fallback.',
      );
      return true;
    }());

    return theme.brightness == Brightness.dark
        ? AppColors.dark()
        : AppColors.light();
  }
}
